services:
  master:
    build: .
    container_name: pdc-master
    volumes:
      - ./hostfile:/app/hostfile
    command: >
      sh -c "/usr/sbin/sshd & sleep 5 && mpirun -np 4 --hostfile /app/hostfile --allow-run-as-root /app/mpi_task"
    networks:
      - pdcn

  worker1:
    build: .
    container_name: pdc-worker1
    command: /usr/sbin/sshd -D
    networks:
      - pdcn

  worker2:
    build: .
    container_name: pdc-worker2
    command: /usr/sbin/sshd -D
    networks:
      - pdcn

  worker3:
    build: .
    container_name: pdc-worker3
    command: /usr/sbin/sshd -D
    networks:
      - pdcn

networks:
  pdcn:
    driver: bridge